backend:
    restart: always
    build: backend
    volumes: 
        - ./backend:/work/backend
    #Change ports to expose becose we are using nginx
    expose:
        - "8000"
    ports:
        - "82:8000"
    working_dir: /work/backend
    command: python main.py
    hostname: docker_python
    links:
        - mongodb

mongodb:
    restart: always
    build: db_mongo
    expose:
        - "27017"
    ports:
        - "27017:27017"
    environment:
        - MONGODB_PASS=dev
        - AUTH=yes

nginx:
    restart: always
    build: frontend
    volumes:
        - ./frontend/static_files/huoliduo:/huoliduo
        - ./frontend/.htpasswd:/etc/nginx/.htpasswd
    ports:
        - "80:80"
        - "81:81"
        - "443:443"
    links:
        - backend